name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
       
      # Step 5: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

    # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t devops-demo .
